INSERT INTO Player (name, user, team, position, lineUp, points, price, state) VALUES

('Joselu', '', 'Alaves', 'DL', 0, 50, 10.0, 'Disponible'),
('Rodrigo Ely', '', 'Alaves', 'MC', 0, 40, 8.5, 'Lesionado'),
('Ximo Navarro', '', 'Alaves', 'DF', 0, 60, 12.0, 'Duda'),
('Luis Rioja', '', 'Alaves', 'PT', 0, 30, 7.0, 'Roja'),
('Borja Sainz', '', 'Alaves', 'DF', 0, 45, 9.5, 'Disponible'),

('Ager Aketxe', '', 'Almeria', 'DL', 0, 45, 9.5, 'Lesionado'),
('Fran Villalba', '', 'Almeria', 'MC', 0, 55, 11.0, 'Duda'),
('Ivan Balliu', '', 'Almeria', 'DF', 0, 42, 8.8, 'Roja'),
('Largie Ramazani', '', 'Almeria', 'PT', 0, 48, 10.2, 'Disponible'),
('Juan Villar', '', 'Almeria', 'DL', 0, 38, 8.0, 'Disponible'),

('Iñigo Martínez', '', 'Athletic Club', 'DL', 0, 60, 12.0, 'Lesionado'),
('Unai Vencedor', '', 'Athletic Club', 'MC', 0, 30, 7.0, 'Duda'),
('Yuri Berchiche', '', 'Athletic Club', 'DF', 0, 45, 9.5, 'Roja'),
('Raúl García', '', 'Athletic Club', 'PT', 0, 55, 11.0, 'Disponible'),
('Iker Muniain', '', 'Athletic Club', 'DL', 0, 60, 12.0, 'Disponible'),

('João Félix', '', 'Atletico de Madrid', 'DL', 0, 38, 8.0, 'Disponible'),
('Koke', '', 'Atletico de Madrid', 'MC', 0, 47, 9.7, 'Disponible'),
('Stefan Savic', '', 'Atletico de Madrid', 'DF', 0, 50, 10.0, 'Lesionado'),
('Luis Suárez', '', 'Atletico de Madrid', 'PT', 0, 40, 8.5, 'Duda'),
('Marcos Llorente', '', 'Atletico de Madrid', 'DL', 0, 45, 9.5, 'Roja'),

('Lionel Messi', '', 'FC Barcelona', 'DL', 0, 45, 9.5, 'Disponible'),
('Frenkie de Jong', '', 'FC Barcelona', 'MC', 0, 55, 11.0, 'Disponible'),
('Gerard Piqué', '', 'FC Barcelona', 'DF', 0, 42, 8.8, 'Lesionado'),
('Antoine Griezmann', '', 'FC Barcelona', 'PT', 0, 48, 10.2, 'Duda'),
('Pedri', '', 'FC Barcelona', 'DL', 0, 60, 12.0, 'Roja'),

('Nabil Fekir', '', 'Real Betis', 'DL', 0, 50, 10.0, 'Duda'),
('Guido Rodríguez', '', 'Real Betis', 'MC', 0, 40, 8.5, 'Disponible'),
('Mandi', '', 'Real Betis', 'DF', 0, 60, 12.0, 'Lesionado'),
('Joaquín', '', 'Real Betis', 'PT', 0, 30, 7.0, 'Roja'),
('Emerson Royal', '', 'Real Betis', 'DF', 0, 45, 9.5, 'Disponible'),

('Álvaro Negredo', '', 'Cadiz', 'DL', 0, 45, 9.5, 'Disponible'),
('Jon Ander Garrido', '', 'Cadiz', 'MC', 0, 55, 11.0, 'Disponible'),
('Isaac Carcelén', '', 'Cadiz', 'DF', 0, 42, 8.8, 'Duda'),
('Salvi Sánchez', '', 'Cadiz', 'PT', 0, 48, 10.2, 'Lesionado'),
('Anthony Lozano', '', 'Cadiz', 'DL', 0, 38, 8.0, 'Roja'),

('Iago Aspas', '', 'Celta de Vigo', 'DL', 0, 60, 12.0, 'Disponible'),
('Nolito', '', 'Celta de Vigo', 'MC', 0, 30, 7.0, 'Duda'),
('Joseph Aidoo', '', 'Celta de Vigo', 'DF', 0, 45, 9.5, 'Lesionado'),
('Denis Suárez', '', 'Celta de Vigo', 'PT', 0, 55, 11.0, 'Roja'),
('Santi Mina', '', 'Celta de Vigo', 'DL', 0, 60, 12.0, 'Disponible'),

('Ángel Rodríguez', '', 'Getafe', 'DL', 0, 45, 9.5, 'Roja'),
('Mauro Arambarri', '', 'Getafe', 'MC', 0, 55, 11.0, 'Disponible'),
('Djené Dakonam', '', 'Getafe', 'DF', 0, 42, 8.8, 'Lesionado'),
('Enes Ünal', '', 'Getafe', 'PT', 0, 48, 10.2, 'Duda'),
('Carles Aleñá', '', 'Getafe', 'DL', 0, 60, 12.0, 'Disponible'),

('Stuani', '', 'Girona', 'DL', 0, 38, 8.0, 'Disponible'),
('Samuel Sáiz', '', 'Girona', 'MC', 0, 47, 9.7, 'Roja'),
('Bernardo Espinosa', '', 'Girona', 'DF', 0, 50, 10.0, 'Lesionado'),
('Jordi Calavera', '', 'Girona', 'PT', 0, 40, 8.5, 'Duda'),
('Franquesa', '', 'Girona', 'DL', 0, 45, 9.5, 'Disponible'),

('Roberto Soldado', '', 'Granada', 'DL', 0, 45, 9.5, 'Duda'),
('Yangel Herrera', '', 'Granada', 'MC', 0, 55, 11.0, 'Disponible'),
('Domingos Duarte', '', 'Granada', 'DF', 0, 42, 8.8, 'Lesionado'),
('Luis Milla', '', 'Granada', 'PT', 0, 48, 10.2, 'Roja'),
('Ángel Montoro', '', 'Granada', 'DL', 0, 60, 12.0, 'Disponible'),

('Sergio Araujo', '', 'Las Palmas', 'DL', 0, 60, 12.0, 'Disponible'),
('Maikel Mesa', '', 'Las Palmas', 'MC', 0, 30, 7.0, 'Duda'),
('Álvaro Lemos', '', 'Las Palmas', 'DF', 0, 45, 9.5, 'Lesionado'),
('Rober', '', 'Las Palmas', 'PT', 0, 55, 11.0, 'Roja'),
('Jesús Fortes', '', 'Las Palmas', 'DL', 0, 45, 9.5, 'Disponible'),

('Abdon Prats', '', 'Mallorca', 'DL', 0, 45, 9.5, 'Duda'),
('Luis García', '', 'Mallorca', 'MC', 0, 55, 11.0, 'Disponible'),
('Fran Gámez', '', 'Mallorca', 'DF', 0, 42, 8.8, 'Lesionado'),
('Amath Ndiaye', '', 'Mallorca', 'PT', 0, 48, 10.2, 'Roja'),
('Jordi Mboula', '', 'Mallorca', 'DL', 0, 60, 12.0, 'Disponible'),

('Rubén García', '', 'Osasuna', 'DL', 0, 45, 9.5, 'Roja'),
('Oier Sanjurjo', '', 'Osasuna', 'MC', 0, 55, 11.0, 'Disponible'),
('Unai García', '', 'Osasuna', 'DF', 0, 42, 8.8, 'Lesionado'),
('Ante Budimir', '', 'Osasuna', 'PT', 0, 48, 10.2, 'Duda'),
('Javi Martínez', '', 'Osasuna', 'DL', 0, 60, 12.0, 'Disponible'),

('Alexander Isak', '', 'Real Sociedad', 'DL', 0, 45, 9.5, 'Duda'),
('Mikel Merino', '', 'Real Sociedad', 'MC', 0, 55, 11.0, 'Disponible'),
('Diego Llorente', '', 'Real Sociedad', 'DF', 0, 42, 8.8, 'Lesionado'),
('Adnan Januzaj', '', 'Real Sociedad', 'PT', 0, 48, 10.2, 'Roja'),
('Portu', '', 'Real Sociedad', 'DL', 0, 60, 12.0, 'Disponible'),

('Óscar Trejo', '', 'Rayo Vallecano', 'DL', 0, 45, 9.5, 'Duda'),
('Santi Comesaña', '', 'Rayo Vallecano', 'MC', 0, 55, 11.0, 'Disponible'),
('Saveljich', '', 'Rayo Vallecano', 'DF', 0, 42, 8.8, 'Lesionado'),
('Álvaro García', '', 'Rayo Vallecano', 'PT', 0, 48, 10.2, 'Roja'),
('Bebe', '', 'Rayo Vallecano', 'DL', 0, 60, 12.0, 'Disponible'),

('Karim Benzema', '', 'Real Madrid', 'DL', 0, 50, 10.0, 'Disponible'),
('Luka Modric', '', 'Real Madrid', 'MC', 0, 40, 8.5, 'Duda'),
('Sergio Ramos', '', 'Real Madrid', 'DF', 0, 60, 12.0, 'Lesionado'),
('Thibaut Courtois', '', 'Real Madrid', 'PT', 0, 30, 7.0, 'Roja'),
('Lucas Vázquez', '', 'Real Madrid', 'DL', 0, 45, 9.5, 'Disponible'),

('Youssef En-Nesyri', '', 'Sevilla', 'DL', 0, 45, 9.5, 'Duda'),
('Joan Jordán', '', 'Sevilla', 'MC', 0, 55, 11.0, 'Disponible'),
('Diego Carlos', '', 'Sevilla', 'DF', 0, 42, 8.8, 'Lesionado'),
('Luuk de Jong', '', 'Sevilla', 'PT', 0, 48, 10.2, 'Roja'),
('Jesús Navas', '', 'Sevilla', 'DL', 0, 60, 12.0, 'Disponible'),

('Maxi Gómez', '', 'Valencia', 'DL', 0, 45, 9.5, 'Duda'),
('Carlos Soler', '', 'Valencia', 'MC', 0, 55, 11.0, 'Disponible'),
('José Gayà', '', 'Valencia', 'DF', 0, 42, 8.8, 'Lesionado'),
('Gonçalo Guedes', '', 'Valencia', 'PT', 0, 48, 10.2, 'Roja'),
('Manu Vallejo', '', 'Valencia', 'DL', 0, 60, 12.0, 'Disponible'),

('Gerard Moreno', '', 'Villarreal', 'DL', 0, 45, 9.5, 'Duda'),
('Dani Parejo', '', 'Villarreal', 'MC', 0, 55, 11.0, 'Disponible'),
('Pau Torres', '', 'Villarreal', 'DF', 0, 42, 8.8, 'Lesionado'),
('Paco Alcácer', '', 'Villarreal', 'PT', 0, 48, 10.2, 'Disponible'),
('Yeremy Pino', '', 'Villarreal', 'DL', 0, 60, 12.0, 'Disponible');